"""Initial revision

Revision ID: 9c55c882b3ab
Revises: 
Create Date: 2023-09-02 17:07:33.408735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ARRAY


# revision identifiers, used by Alembic.
revision: str = '9c55c882b3ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_refresh_token'), 'refresh_tokens', ['refresh_token'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer()),
    sa.Column('name', sa.String(), nullable=False, unique=True),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False, unique=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), primary_key=True),
    sa.Column('name', sa.String(), nullable=False, unique=True),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False, unique=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('rented_days', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('addressess',
    sa.Column('id', sa.Integer(), primary_key=True),
    sa.Column('address', sa.String(), nullable=False, unique=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('problems',
    sa.Column('id', sa.Integer(), primary_key=True),
    sa.Column('title', sa.String(), nullable=False, unique=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('collected', sa.Integer(), nullable=False),
    sa.Column('necessary', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('main_pages',
    sa.Column('id', sa.Integer(), primary_key=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('supertitle', sa.String(), nullable=True),
    sa.Column('subtitle', sa.String(), nullable=False),
    sa.Column('history_block', sa.String(), nullable=False),
    sa.Column('main_image', sa.String(), nullable=False),
    sa.Column('carousel_image', ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id')
)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_refresh_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('services')
    op.drop_table('addressess')
    op.drop_table('problems')
    op.drop_table('main_pages')
    # ### end Alembic commands ###
